config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('accounts/', include('accounts.urls')),
    path('photo/', include('photo_gallery.urls')),
]
# 우리들의서버주소/polls

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
# from . import views
# 원하는 뷰를 가져오는 형태
from .views import lion, dubug_request, memo_list, memo_detail, index,memo_create,test1,test2
# from polls import views
# from polls.views import lion, dubug_request
from . import views
# app_name 부여하고, urlpattern에 이름 넣고
# html에서 a태그(링크)부분에
# {% url '앱네임:url이름' %} 넣어서
# 잘 동작하는지 확인해보겠습니다!
app_name = 'polls'

urlpatterns = [   
    path('',index, name='index'),
    path('memo/', memo_list, name='memo_list'),
    path('memo/mine/',views.my_memo_list,name="my_memo_list"),
    path('memo/<int:pk>/', memo_detail, name='memo_detail'),
    path('memo/create/',memo_create, name='memo_create'),
    path('test1/', test1, name='test1'),
    path('test2/',test2,name='test2'),
    path('memo/update/<int:pk>/', views.memo_update, name='memo_update'),
    path('memo/delete/<int:pk>/', views.memo_delete, name='memo_delete'),
    path('memo/search', views.memo_search, name='memo_search')
    # path('tiger/<str:name>/', lion),
    # path('', index),
    # path('bad/', blog_list),
    # 127.0.0.1/dubug/  => path('dubug/', dubug_request)
]
# url이 어떻게 뷰로 연결되는지 원리를 이해.

polls/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
"""
CREATE TABLE customers (
    customer_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(20),
    investment_style VARCHAR(20) DEFAULT '보수적'
        CHECK (investment_style IN ('보수적', '적극적', '공격적')),
    vip_flag BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""

class Article(models.Model):
    title = models.CharField('제목', max_length=200)
    content = models.TextField("content")
    created_at = models.DateTimeField('작성일', auto_now_add=True)
    updated_at = models.DateTimeField('수정일', auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "아티클"
        verbose_name_plural = "아티클들"

# models.py에 Table을 파이썬 코드로 작성합니다!
# 설계도 작성 : python manage.py makemigrations
# 실제 DB에 반영 : python manage.py migrate

# 여러분의 DB에 테이블을 생성해 보겠습니다!

# author 추가
# 디버그에서 view에 index에서 브레이크 포인트로 멈추기
# 디버그 콘솔에서 Memo 내용을 조회
# from django.contrib.auth.models import User
# user = User.objects.get(pk=1)
# user.memos.all()
class Memo(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='memos',
        verbose_name='작성자'
    )
    title = models.CharField('제목', max_length=100)
    content = models.TextField('내용')
    is_important = models.BooleanField('중요', default=False)
    created_at = models.DateTimeField('생성일', auto_now_add=True)

    def __str__(self):
        return self.title
    class Meta:
        verbose_name = '메모'
        verbose_name_plural = '메모 목록'
        ordering = ['-created_at']  # 최신순 정렬

# -> Admin 페이지 등록
# 2시 50분까지

# 3시 부터는 뷰를 같이 만들어 보기기

polls/forms.py
from django import forms
from .models import Memo

class MemoModelForm(forms.ModelForm):
    class Meta:
        model = Memo
        fields = ['title','content','is_important']

polls/views.py
# polls/views.py에 간단한 뷰 작성
from django.contrib.auth.forms import User
from django.http import HttpResponse

# 장고 페이지 구성의 핵심
from django.shortcuts import get_object_or_404, redirect, render
from .models import Article, Memo

# index에서 context 만들어서 보내기기
def index(request):
    return render(request=request,template_name="polls/index.html")
    
# def blog_list(request):
#     return render(request,"not_good.html")

def lion(request,name):
    return HttpResponse(f"""{name}가 장고를 배웁니다!!""")

# 내가 request라는 객체가 생소한데, 안에 어떤 내용들이 있는지 확인해 보고 싶어
# 이거를 하나의 뷰로 만들어서 웹에 표시해 볼까?
# 디버그 하는 역할 이네 -> dubug_request로 이름짓자
def dubug_request(request):
    # request 의 메서드와
    # request 의 path
    # request 의 META.REMOTE_ADDR를 화면에 표시하자!!
    content = f"""이것이 request가 가지고 있는 정보의 예시입니다.<br>
    request.path = {request.path}    <br>
    request.method = {request.method}    <br>
    request.META.REMOTE_ADDR = {request.META.get('REMOTE_ADDR', 'Unknown')}    <br>
    """
    return HttpResponse(content)

# 디버그 버튼누르시고, launch.json파일 만들기 선택(우리가 디버그 설정을 직접 관리하는 방법)
# 엉뚱한 디버그들 선택해 보기(실수를 해도 스트레스 받지 않기?!)
# 생성된 launch.json을 삭제하고 다시 장고 디버그 설정으로 수정하기
# 디버그 가동(F5 또는 디버그 버튼 클릭)
# 디버그 뷰에서 브레이크 포인트 잡기(코드 왼쪽 숫자의 왼쪽을 클릭, 또는 f9)
# 해당 포인트에 멈추게 해보기!!(서버를 가동하고 해당 뷰가 호출되도록 브라우저에서 주소 입력)
# 디버그 콘솔에서 이것저것 해보기기
# 9시 50분까지 하겠습니다!!!




# 여러개 여러분 마음대로 만들어 보세요!

# view 만들기
# polls에 urls.py 작성
# path("경로",뷰함수)

# config urls.py
# path("아무거나경로", inclued(polls.urls))

# 브라우저에서 확인


# 3시 20분까지
# 각 url로 접근하여 페이지가 나오도록 해보겠습니다.
# 1. /polls/hello/ -> "안녕하세요" 라고 페이지에 표시하기
# 2. /polls/good/ -> AI를 통해 작성된 다양한 페이지 표시하기

# 2시 40분까지 ORM 체험해 보겠습니다~!

# 메모리스트를 보여주는 뷰를 만들어 보겠습니다.
def memo_list(request):
    # 메모 전체 가져오기
    memos=Memo.objects.all()
    # # content 구성하기
    # content=""
    # for memo in all_memo:
    #     content += "제목 : "+memo.title+"<br>"
    #     content += "내용 : "+memo.content+"<br>"
    #     content += "----"*10
    #     content += "<br>"
    context = {
        "memos":memos
    }
    return render(request, 'polls/memo_list.html', context)

def test1(request):
    return render(request, 'polls/index.html')

def test2(request):
    return render(request,'polls/test2.html')

from .forms import MemoModelForm
from django.contrib.auth.decorators import login_required

# update와 delete 기능을 개발해 보겠습니다!!
# 그냥 개발 시작해 보시고
# 막히는 부분 있으면 교안 또는 직원 참고해서 완성해 보겠습니다!
# 10:50 까지 하겠습니다!


@login_required
def memo_create(request):
    if request.method=="POST":
        # title = request.POST.get['title']
        # form??
        # return ??
        form = MemoModelForm(request.POST)
        if form.is_valid():
            # 직접 입력되지 않는 정보(ex- user)를 추가 입력할때는 form.save(commit=False)를 사용한다!
            user= User.objects.get(pk=request.POST['author'])
            memo=form.save(commit=False)            
            memo.author=user
            memo.save()
            # 
            #-------------------------------------------------
            # 1. 메모리스트? list
            # return redirect('polls:memo_list')
            # 2. 지금 작성한 메모를 보여주기? detail
            #-------------------------------------------------
            return redirect('polls:memo_detail',pk=memo.id)
        # 1.form을 이용해서 저장하는 프로세스 체크
        # 2.페이지 요청할때, 인자를 담아서 보내기
        # 3. 과제 -> memo detail 페이지 기존에 하드코딩된 형태에서 template이용한 내용으로 변경하기기
        # 9시 50분까지 진행해 보겠습니다!

    else:
        form = MemoModelForm()
        return render(request, 'polls/memo_create.html', context={'form':form})
    # # step 1
    # # 고객이 입력할 수 있는 화면 보여주기
    # if request.method=='GET':
    #     return render(request,'polls/memo_create.html')
    # # step 2
    # # 고객이 입력한 정보를 확인 -> 고객이 입력한 정보 어디있나?
    # # title, content
    # # Memo에 입력
    # # 다음 페이지로 보내기
    # else:
    #     title = request.POST.get('title','no_title') # request.POST['title']
    #     content = request.POST.get('content','no content')
    #     Memo.objects.create(title=title, content=content)
    #     return redirect('polls:memo_list')       

# content = "제목 : 타이틀
# 내용 : 콘텐트
# 제목 : 타이틀
# 내용 : 콘텐트
# 제목 : 타이틀
# 내용 : 콘텐트
# " 줄바꿈 -> <br>
@login_required
def my_memo_list(request):

    # memos=Memo.objects.filter(author=request.user)
    memos = request.user.memos.all()

    context = {
        "memos":memos
    }
    return render(request, 'polls/my_memo_list.html', context)


def memo_detail(request, pk):
    # memo = Memo.objects.get(id=pk)
    memo = get_object_or_404(Memo, pk=pk)
    return render(request,'polls/memo_detail.html', {"memo":memo})
    # content = f"""<h1>제목 : {memo.title}</h1> <br><br> 
    # 내용 : {memo.content}<br>
    # {memo.is_important}<br>
    # {memo.created_at}
    # """
    # return HttpResponse(content)
from django.contrib import messages
@login_required
def memo_update(request, pk):
    """메모 수정 - 작성자만 가능"""
    memo = get_object_or_404(Memo, pk=pk)

    # 작성자 확인
    if memo.author != request.user:
        messages.error(request, '자신의 메모만 수정할 수 있습니다.')
        return redirect('polls:memo_detail', pk=pk)

    if request.method == 'POST':
        form = MemoModelForm(request.POST, instance=memo)
        if form.is_valid():
            form.save()
            messages.success(request, '메모가 수정되었습니다.')
            return redirect('polls:memo_detail', pk=pk)
    else:
        form = MemoModelForm(instance=memo)

    return render(request, 'polls/memo_form.html', {
        'form': form,
        'is_update': True
    })

from django.core.exceptions import PermissionDenied
@login_required
def memo_delete(request, pk):
    """메모 삭제 - 작성자만 가능"""
    memo = get_object_or_404(Memo, pk=pk)

    # 작성자 확인
    if memo.author != request.user:
        raise PermissionDenied('삭제 권한이 없습니다.')

    if request.method == 'POST':
        memo.delete()
        messages.success(request, '메모가 삭제되었습니다.')
        return redirect('polls:memo_list')

    return render(request, 'polls/memo_confirm_delete.html', {'memo': memo})
# 1. CRUD
# 2. Update Delete에 해당하는 뷰, 템플릿 구성
# 3. 각 템플릿에 base.html 적용

from django.db.models import Q
def memo_search(request):
    query = request.GET.get('q',"")
    memos = Memo.objects.filter(
        Q(title__icontains=query) | Q(content__icontains=query)
    )
    context = {
        "memos": memos,
        "query": query
    }
    return render(request, 'polls/memo_list.html', context)

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {%block lion%} {%endblock%}
    <h1> 이거는 {%block name%}polls/base.html{%endblock%}의 내용입니다.</h1>
    {%block content%}{%endblock%}
</body>
</html>

polls/templates/polls/demo_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>My First Django</h1>
    {{name}}<br>

    {# memos 정보가 있으면, for 문을 통해서 출력 #}
    {# 전달받은 내용 출력하기 #}
    {# 11시 40분까지 실습하겠습니다! #}
    {% if memos %}
        {% for memo in memos %}
            <h7>{{memo.id}} {{memo.title}}</h7>
            <p>{{memo.content}}</p>
        {% endfor %}
    {% else %}
        <h3>메모 내용이 없습니다</h3>
    {% endif %}
</body>
</html>

polls/templates/polls/index.html
{% extends 'common/base.html' %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-8">
            <h1>장고 템플릿 연습</h1>
            <p>안녕하세요, {{name}}님!</p>
            <p>{{context}}</p>
            
            <img src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRvbEOG2k2LPoZdHP7tN2q1IrNRgtPn26I5TU7kBvlw_7FgWpmQQ3o3pI9HTaY-pEOTsNqSjyg2kCFEg6evEGwUKg" 
                 class="img-fluid rounded mb-3" alt="Django Logo">
            
            {# 메모가 있으면, for문을 진행 #}
            {% if memos %}
                <h2>메모 목록</h2>
                <ul class="list-group">
                {% for memo in memos %}
                    <li class="list-group-item">
                        <strong>{{memo.id}}. {{memo.title}}</strong> - {{memo.content|truncatewords:10}}
                    </li>
                {% endfor %}
                </ul>
            {% else %}
                <p class="text-muted">등록된 메모가 없습니다.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

polls/templates/polls/memo_confirm_delete.html
<!-- memo_confirm_delete.html -->
<!DOCTYPE html>
<html>
<head>
    <title>메모 삭제</title>
</head>
<body>
    <h1>메모 삭제 확인</h1>
    <p>정말로 "{{ memo.title }}" 메모를 삭제하시겠습니까?</p>

    <form method="POST">
        {% csrf_token %}
        <button type="submit">삭제</button>
        <a href="{% url 'polls:memo_detail' memo.pk %}">취소</a>
    </form>
</body>
</html>

polls/templates/polls/memo_create.html
{% extends 'common/base.html' %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="hidden" name="author" value="{{user.id}}">
    <button type="submit">저장</button>
</form>
{% endblock %}

polls/templates/polls/memo_detail.html
<!-- memo_detail.html -->
<!DOCTYPE html>
<html>
<head>
    <title>{{ memo.title }}</title>
</head>
<body>
    <h1>{{ memo.title }}</h1>
    {% if memo.is_important %}
        <p>⭐ 중요한 메모</p>
    {% endif %}

    <div style="white-space: pre-wrap;">{{ memo.content }}</div>

    <p>작성일: {{ memo.created_at|date:"Y-m-d H:i:s" }}</p>

    {% if user==memo.user %}
        <a href="{% url 'polls:memo_update' memo.pk %}">수정</a>
        <a href="{% url 'polls:memo_delete' memo.pk %}">삭제</a>
    {% endif %}
    <a href="{% url 'polls:memo_list' %}">목록으로</a>
</body>
</html>

polls/templates/polls/memo_list.html
{% extends 'common/base.html' %}

{% block content %}
<div class="container mt-4" style="max-width: 900px;">
    <h1 class="mb-4 fw-bold" style="color: #7c3aed;">나의 메모 목록</h1>
    {% if memos %}
        <div class="row">
        {% for memo in memos %}
            <div class="col-md-6 mb-4">
                <div class="card shadow border-0" style="border-left: 6px solid #7c3aed;">
                    <div class="card-header text-white fw-bold" style="background: #7c3aed;">
                        {{ memo.title }}
                    </div>
                    <div class="card-body">
                        <h6 class="card-subtitle mb-2 text-muted">ID: {{ memo.id }}</h6>
                        <p class="card-text">{{ memo.content }}</p>
                        <a href="{% url 'polls:memo_detail' memo.id %}" class="btn btn-sm text-white" style="background: #7c3aed;">
                            상세 보기
                        </a>
                    </div>
                    <div class="card-footer text-end" style="background: #ede9fe;">
                        <small class="text-muted">{{ memo.created_at|date:"Y-m-d H:i" }}</small>
                        {% if memo.is_important %}
                            <span class="badge rounded-pill text-bg-warning ms-2">중요</span>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <div class="alert text-white" style="background: #7c3aed;" role="alert">
            메모가 없습니다.
        </div>
    {% endif %}
</div>
<style>
    .border-violet {
        border-color: #7c3aed !important;
    }
    .bg-violet {
        background: #7c3aed !important;
    }
</style>
{% endblock %}

polls/templates/polls/my_memo_list.html
{% extends 'common/base.html' %}

{% block content %}
<div class="container mt-4" style="max-width: 900px;">
    <h1 class="mb-4 fw-bold" style="color: #7c3aed;">나의 메모 목록</h1>
    {% if memos %}
        <div class="row">
        {% for memo in memos %}
            <div class="col-md-6 mb-4">
                <div class="card shadow border-0" style="border-left: 6px solid #7c3aed;">
                    <div class="card-header text-white fw-bold" style="background: #7c3aed;">
                        {{ memo.title }}
                    </div>
                    <div class="card-body">
                        <h6 class="card-subtitle mb-2 text-muted">ID: {{ memo.id }}</h6>
                        <p class="card-text">{{ memo.content }}</p>
                        <a href="{% url 'polls:memo_detail' memo.id %}" class="btn btn-sm text-white" style="background: #7c3aed;">
                            상세 보기
                        </a>
                    </div>
                    <div class="card-footer text-end" style="background: #ede9fe;">
                        <small class="text-muted">{{ memo.created_at|date:"Y-m-d H:i" }}</small>
                        {% if memo.is_important %}
                            <span class="badge rounded-pill text-bg-warning ms-2">중요</span>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <div class="alert text-white" style="background: #7c3aed;" role="alert">
            메모가 없습니다.
        </div>
    {% endif %}
</div>
<style>
    .border-violet {
        border-color: #7c3aed !important;
    }
    .bg-violet {
        background: #7c3aed !important;
    }
</style>
{% endblock %}

polls/templates/polls/template_test.html
<!-- page1.html -->
<!DOCTYPE html>
<html>
<head>
    <title>페이지 1</title>
    <style>
        body { font-family: Arial; }  <!-- 중복! -->
    </style>
</head>
<body>
    <nav>메뉴</nav>  <!-- 중복! -->
    <h1>페이지 1</h1>
    <footer>Copyright 2024</footer>  <!-- 중복! -->
</body>
</html>

polls/templates/polls/test2.html
{% extends 'polls/base.html' %}
{% block content %}
<h1>i;hdsaf;hfa;hfi;haiofdh</h1>
{% endblock %}